- align: right
  image: adrienne-sutton.jpg
  content: >
    ### Adrienne Sutton
    **Principal Investigator**
    
    *NOAA Pacific Marine Environmental Laboratory, United States*
    
    [NOAA PMEL Profile](https://www.pmel.noaa.gov/co2/story/Adrienne+J.+Sutton,+Ph.D.)

- align: left
  image: galen-mckinley.jpg
  content: >
    ### Galen McKinley
    **Principal Investigator**
    
    *Columbia University and Lamont-Doherty Earth Observatory, United States*
    
    [Personal Website](https://galenmckinley.github.io) | [Lamont Profile](https://lamont.columbia.edu)

- align: right
  image: sandy-thomalla.jpg
  content: >
    ### Sandy Thomalla
    
    *Southern Ocean Carbon-Climate Observatory (SOCCO), CSIR, South Africa*
    
    [SOCCO Team Page](https://socco.org.za/about#team)

- align: left
  image: elizabeth-shadwick.jpg
  content: >
    ### Elizabeth Shadwick
    
    *CSIRO / Australian Antarctic Program Partnership (AAPP), Australia*
    
    [CSIRO Profile](https://people.csiro.au/S/E/Elizabeth-Shadwick)

- align: right
  image: laique-djeutchouang.jpg
  content: >
    ### Laique Merlin Djeutchouang
    
    *Stellenbosch University & SOCCO (CSIR), South Africa*
    
    [Stellenbosch Profile](https://climate.sun.ac.za/team/postdoctoral-research-fellows/)

- align: left
  image: sarah-nicholson.jpg
  content: >
    ### Sarah Nicholson
    
    *Southern Ocean Carbon-Climate Observatory (SOCCO), CSIR, South Africa*
    
    [Personal Website](https://sarahnicholson.github.io/)

- align: right
  image: abby-shaum.jpg
  content: >
    ### Abby Shaum
    
    *Columbia University and Lamont-Doherty Earth Observatory, United States*
    
    [Lamont Profile](https://lamont.columbia.edu/directory/abby-caroline-shaum)

- align: left
  image: bronte-tilbrook.jpg
  content: >
    ### Bronte Tilbrook
    
    *CSIRO / Australian Antarctic Program Partnership (AAPP), Australia*
    
    [CSIRO Profile](https://people.csiro.au/t/b/bronte-tilbrook)

- align: right
  image: thea-heimdal.jpg
  content: >
    ### Thea Hatlen Heimdal
    
    *Columbia University and Lamont-Doherty Earth Observatory, United States*
    
    [Columbia Profile](https://people.climate.columbia.edu/users/profile/thea-heimdal)

- align: left
  image: treasure-warren.jpg
  content: >
    ### Treasure Warren
    
    *University of Washington, School of Oceanography, United States*
    
    [UW Oceanography Profile](https://www.ocean.washington.edu/home/Treasure_Warren)

- align: right
  image: erik-van-ooijen.jpg
  content: >
    ### Erik van Ooijen
    
    *CSIRO / Australian Antarctic Program Partnership (AAPP), Australia*
    
    [CSIRO Profile](https://people.csiro.au/V/E/Erik-Vanooijen)

- align: left
  image: siyabulela-hamnca.jpg
  content: >
    ### Siyabulela Hamnca
    
    *Southern Ocean Carbon-Climate Observatory (SOCCO), CSIR, South Africa*
    
    [SOCCO Team Page](https://socco.org.za/about#team)

- align: right
  image: evan-howard.jpg
  content: >
    ### Evan Howard
    
    *University of Washington (CICOES), United States*
    
    [CICOES Profile](https://cicoes.uw.edu/research/principal-investigators/evan-howard/)

- align: left
  image: amanda-fay.jpg
  content: >
    ### Amanda Fay
    
    *Columbia University and Lamont-Doherty Earth Observatory, United States*
    
    [Lamont Profile](https://lamont.columbia.edu/directory/amanda-r-fay)

- align: right
  image: sarah-nickford.jpg
  content: >
    ### Sarah Nickford
    
    *University of Washington (CICOES), United States*
    
    [CICOES Website](https://cicoes.uw.edu)
